Add World.getHighestBlockAt and getHighestYAt
SpongePowered/SpongeAPI pull request #1416
Opened 2016-11-19 04:03 UTC by Maxqia

**API** | [Common](https://github.com/SpongePowered/SpongeCommon/pull/1015)
This replaces #1381 and fixes #1375.

2016-11-19 04:07 UTC, kashike requested changes

2016-11-19 04:07 UTC, kashike commented on src/main/java/org/spongepowered/api/world/World.java
> +    default Location<World> getHighestBlockAt(Vector3i position) {
Why `Vector3i` and not `Vector2i`?

2016-11-19 04:08 UTC, Maxqia commented on src/main/java/org/spongepowered/api/world/World.java
> +    default Location<World> getHighestBlockAt(Vector3i position) {
"Well it makes it easier to do something like this world.getHighestBlockAt(location.getBlockPosition()). "

2016-11-19 04:17 UTC, JBYoshi commented on src/main/java/org/spongepowered/api/world/World.java
> +    default Location<World> getHighestBlockAt(Vector3i position) {
Maybe you could add a method for both?

2016-11-25 04:42 UTC, Maxqia commented on src/main/java/org/spongepowered/api/world/World.java
> +    default Location<World> getHighestBlockAt(Vector3i position) {
That'd be pointless, nothing with locations uses Vector2i

2017-02-19 22:19 UTC, gabizou requested changes
Checkstyle issues. Documentation style issues.

2017-02-19 22:19 UTC, gabizou commented on src/main/java/org/spongepowered/api/world/Location.java
> +     * @return the highest Location at this Location
New line between description and `@return`

2017-02-19 22:19 UTC, gabizou commented on src/main/java/org/spongepowered/api/world/extent/Extent.java
> +     * Get the y value of the highest block that sunlight can reach in the given column.
Line length is longer than 80 characters. Please run `gradle checkstyle` to fix your warnings.

2017-04-13 08:05 UTC, kashike commented
@Maxqia Able to get this updated?

2017-04-18 03:10 UTC, merged