Add methods for getting entity sounds for an entity
SpongePowered/SpongeAPI pull request #1417
Opened 2016-11-19 06:28 UTC by Maxqia

**API** | [Common](url)
I had this lying around for a month or so..., so here you go!
There might be some sounds missing and if there are, please tell me where I can find them.

2016-11-19 06:57 UTC, liach requested changes

2016-11-19 06:57 UTC, liach commented on src/main/java/org/spongepowered/api/entity/Entity.java
>  }
You need an extra line before this line.

2016-11-19 06:57 UTC, liach commented on src/main/java/org/spongepowered/api/entity/living/Living.java
> +     * @param distance How far the entity fell
You need an extra empty line of Javadoc before this line.

2016-11-19 06:57 UTC, liach commented on src/main/java/org/spongepowered/api/entity/living/Living.java
> +    SoundType getFallSound(int distance);
You should probably use a `double` for such distance.

2016-11-19 06:59 UTC, liach commented
In general, the best way to retrieve a sound is to provide a context.

2016-11-19 10:58 UTC, ST-DDT commented
In https://github.com/SpongePowered/SpongeAPI/pull/1376 / https://github.com/SpongePowered/SpongeAPI/commit/4ae202fa5cfb99824177851c45352863640d3704 we went for `BlockSoundGroup` maybe we should do the same here for `EntitySoundGroup`?

Maybe we could also structure it a little bit:

![soundgroup](https://cloud.githubusercontent.com/assets/1579362/20454948/60d7a7bc-ae4f-11e6-837d-ccce6cdbf6bf.png)

2016-11-19 11:05 UTC, ST-DDT commented
> In general, the best way to retrieve a sound is to provide a context.

@liach What context are you referring to?

2016-11-19 11:49 UTC, ST-DDT requested changes

2016-11-19 11:49 UTC, ST-DDT commented on src/main/java/org/spongepowered/api/entity/living/Living.java
> +     * Gets the volume that the sounds for this entity are played
Missing dot at the end of sentence.

2016-11-19 11:49 UTC, ST-DDT commented on src/main/java/org/spongepowered/api/entity/living/Living.java
> +     * (e.g for if it's a baby)
Missing dot at the end of sentence.

2016-11-19 11:49 UTC, ST-DDT commented on src/main/java/org/spongepowered/api/entity/living/Living.java
> +     * @return The {@link SoundType} that is played when this entity gets hurt
I guess its not necessary to link to the returned class here again.

2016-11-19 11:49 UTC, ST-DDT commented on src/main/java/org/spongepowered/api/entity/living/Living.java
> +     * @return The {@link SoundType} that is played when this entity dies
I guess its not necessary to link to the returned class here again.

2016-11-19 11:49 UTC, ST-DDT commented on src/main/java/org/spongepowered/api/entity/living/Living.java
> +     * @return The {@link SoundType} that is played when this entity falls that distance
I guess its not necessary to link to the returned class here again.

2016-11-19 11:49 UTC, ST-DDT commented on src/main/java/org/spongepowered/api/entity/living/Living.java
> +    SoundType getFallSound(int distance);
Just curious: Is there a difference of sound depending on the fall distance? (I haven't noticed it myself yet, but I just may be deaf.^^)

2016-11-19 11:49 UTC, ST-DDT commented on src/main/java/org/spongepowered/api/entity/Entity.java
> +     * @return The SoundType for noise this entity makes when it swims
IMO these sentences could be simplified to:
````
The sound that the entity emits when it ...
````
Same goes for the other methods. Not 100% sure though.

2016-11-19 16:10 UTC, liach commented on src/main/java/org/spongepowered/api/entity/living/Living.java
> +    SoundType getFallSound(int distance);
Yes, if you have noticed vanilla sound types. There is a small fall and a big fall.

2016-11-19 19:19 UTC, Maxqia commented
I did it mainly for simplicity of the implementation, because the methods and fields for getting sounds for entities are in the entity class, while block sounds are in a different class.

2016-11-20 19:09 UTC, Minecrell commented
@Maxqia 
In my opinion the structure @ST-DDT suggested makes sense and is actually quite simple to implement:

It shouldn't take long to create another class in the implementation that links to the internal Entity class and just returns the sounds. If you really have to you could even make the internal Entity class implement `EntitySoundGroup` directly and just return `this` when `getSoundGroup()` is called on `Entity`.

The purpose of SpongeAPI is not to represent the internal classes exactly but to hide most of the internal structure and provide it in a logical way to plugin developers.

2016-11-25 04:49 UTC, Maxqia commented
I might make it actually so that BlockSoundGroup is integrated into BlockType, because making a soundgroup for (practically) every entity is going to make me lose my sanity :P

2016-12-09 12:22 UTC, kashike commented
@Maxqia Status on the comments above?

2017-04-13 08:06 UTC, kashike commented
@Maxqia Status on the comments above?

2017-08-10 21:52 UTC, closed without merging

2017-08-10 22:04 UTC, Zidane commented
@kashike is taking over this PR.