EnderDragon phases
SpongePowered/SpongeAPI pull request #1421
Opened 2016-11-25 00:35 UTC by kashike

[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1421) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/1032)
Adds #1273.

2016-11-25 00:57 UTC, liach requested changes

2016-11-25 00:57 UTC, liach commented on src/main/java/org/spongepowered/api/entity/living/complex/dragon/phase/EnderDragonPhase.java
> +}
line

2016-11-25 00:57 UTC, liach commented on src/main/java/org/spongepowered/api/entity/living/complex/dragon/phase/EnderDragonPhaseManager.java
> +}
line

2016-11-25 00:57 UTC, liach commented on src/main/java/org/spongepowered/api/entity/living/complex/dragon/phase/EnderDragonPhaseTypes.java
> +}
line

2016-11-25 05:34 UTC, gabizou commented on src/main/java/org/spongepowered/api/entity/living/complex/dragon/phase/EnderDragonPhaseType.java
> +public interface EnderDragonPhaseType {
Not a `CatalogType`?

2016-11-25 05:35 UTC, gabizou commented on src/main/java/org/spongepowered/api/entity/living/complex/dragon/phase/EnderDragonPhaseTypes.java
> +    public static final EnderDragonPhaseType DYING = DummyObjectProvider.createFor(EnderDragonPhaseType.class, "DYING");
If you can, please document what these phases mean and what they're supposed to do, since there's no AI for this sort of thing, it's all dependent on the phase itself.

2016-11-25 08:08 UTC, gabizou commented on src/main/java/org/spongepowered/api/entity/living/complex/EnderDragon.java
> +     * Gets the phase manager.
Care to elaborate what the phase manager does? Remember, for us working in implementation, we know exactly what it does, but to plugin developers, it's completely foreign.

2016-11-25 08:42 UTC, liach commented on src/main/java/org/spongepowered/api/entity/living/complex/EnderDragon.java
> +     * Gets the phase manager.
Added below already.

2017-02-25 07:01 UTC, gabizou requested changes
Could add some more, such as some events when the phases change.

2017-02-25 07:01 UTC, gabizou commented on src/main/java/org/spongepowered/api/entity/living/complex/dragon/phase/EnderDragonPhaseManager.java
> +
Could you expose a little more to this interface to "pad" it so it's not just looking as though it's a wrapper around what the current phase of the dragon is? Perhaps, adding a getter for the actual `EnderDragon` that is being managed?

2017-12-16 04:09 UTC, liach commented
@kashike After my investigation, I find it possible for plugins to add custom phases on server side. Would you add that feature?

2017-12-16 04:14 UTC, liach commented
I also suggest putting the phases into ai package instead: they use the path finder to navigate for the dragon, and the vanilla ai task set was completely untouched.

2018-01-27 11:41 UTC, ryantheleach commented
This was stalled by an interaction with the associated implementation PR with the old cause tracker, it should now be unblocked but needs to be updated for the new Phase/Cause Stack system.

2018-08-30 06:04 UTC, gabizou commented
I was considering positioning this for API 7, as possibly more content to get added, but as the implementation is needing updating, this will be on the back burner.

2019-01-30 05:02 UTC, liach commented on src/main/java/org/spongepowered/api/entity/living/complex/EnderDragon.java
> +    EnderDragonPhaseManager getPhaseManager();
Does this belong to the dragon itself or the dragon's data?

2019-01-30 05:04 UTC, liach commented on src/main/java/org/spongepowered/api/entity/living/complex/dragon/phase/EnderDragonPhaseManager.java
> +    void setPhase(EnderDragonPhaseType phase);
Should return the new phase that ships the target location.

2019-02-03 16:55 UTC, gabizou approved these changes

2019-02-03 16:58 UTC, merged