[WIP] Added location-based AI tasks.
SpongePowered/SpongeAPI pull request #1470
Opened 2017-01-25 12:37 UTC by me4502

SpongeAPI | SpongeCommon

This WIP PR is to add vanilla location-based AI tasks. The intention is to make it easier for plugins to control the movement of entities.

2017-01-25 14:36 UTC, liach commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +}
line

2017-01-25 14:38 UTC, liach commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +        MoveToBlockAITask.Builder destinationPredicate(Predicate<Location<World>> destinationPredicate);
```java
MoveToBlockAITask.Builder destination(Location<World> destination);
```
for consistency.

2017-01-25 14:39 UTC, liach commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +        MoveToBlockAITask.Builder destinationPredicate(Predicate<Location<World>> destinationPredicate);
Or to change the checker above.

2017-01-25 14:40 UTC, liach commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +public interface MoveToBlockAITask extends AITask<Creature> {
This class has subclasses that takes a different type of owner.

2017-01-25 14:47 UTC, liach commented
You need to add javadocs.

2017-01-25 22:20 UTC, liach commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +    int getSearchRange();
You should add `MoveToBlockAITask setSpeed(double speed)` and `MoveToBlockAITask setSearchRange(int searchRange)` methods.

2017-01-25 23:13 UTC, me4502 commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +        MoveToBlockAITask.Builder destinationPredicate(Predicate<Location<World>> destinationPredicate);
I didn't include that in the builder as it doesn't really make sense, it's something that's set later to override the current state.

2017-01-25 23:30 UTC, liach commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +        MoveToBlockAITask.Builder destinationPredicate(Predicate<Location<World>> destinationPredicate);
I suggest to remove the setter above.

2017-01-26 00:37 UTC, liach requested changes

2017-01-26 00:37 UTC, liach commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +public interface MoveToBlockAITask extends AITask<Creature> {
Since this is just one file, you should javadoc it.

2017-01-26 00:37 UTC, liach commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +    MoveToBlockAITask setDestination(Vector3i destination);
This should be removed in favor of the predicate.

2017-01-26 00:47 UTC, me4502 commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +        MoveToBlockAITask.Builder destinationPredicate(Predicate<Location<World>> destinationPredicate);
Which setter?

2017-01-26 00:48 UTC, me4502 commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +    MoveToBlockAITask setDestination(Vector3i destination);
The predicate is awfully slow if you just want to set a specific block.

2017-01-26 00:51 UTC, windy1 commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +    MoveToBlockAITask setDestination(Vector3i destination);
@liach why?

2017-01-26 01:10 UTC, liach commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +    MoveToBlockAITask setDestination(Vector3i destination);
E.g. if you set a pos in a lava as the target. The predicate checks gradually.

2017-01-27 04:32 UTC, liach requested changes

2017-01-27 04:32 UTC, liach commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +package org.spongepowered.api.entity.ai.task.builtin.creature.location;
Where is the package info file? I suggest renaming the package to `path` or similar.

2017-01-27 23:46 UTC, me4502 commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +package org.spongepowered.api.entity.ai.task.builtin.creature.location;
I have a package info file, git doesn't appear to see it for some reason

2017-01-28 00:31 UTC, liach commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +package org.spongepowered.api.entity.ai.task.builtin.creature.location;
will wait for your next push 😄

2017-01-28 00:46 UTC, liach commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/package-info.java
> +@org.spongepowered.api.util.annotation.NonnullByDefault package org.spongepowered.api.entity.ai.task.builtin.creature.location;
Should there be a new line in the end?

2017-01-29 02:31 UTC, liach commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/package-info.java
> - * This file is part of Sponge, licensed under the MIT License (MIT).
😆

2017-01-29 06:50 UTC, liach commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +        MoveToBlockAITask.Builder destinationPredicate(Predicate<Location<World>> destinationPredicate);
`MoveToBlockAITask setDestination(Vector3i destination);`

2017-01-29 16:30 UTC, liach commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/package-info.java
> +@org.spongepowered.api.util.annotation.NonnullByDefault package org.spongepowered.api.entity.ai.task.builtin.creature.location;
Done. 👍

2017-01-29 17:20 UTC, liach approved these changes
Well, try to add JavaDoc if you can...

2017-01-30 16:15 UTC, liach commented
I think this is done. Why is this still WIP?

2017-02-03 23:39 UTC, me4502 commented
@Zidane As you did the original AI tasks, are you able to look over this and basically tell me what you think of it?

The goal is to allow a simple way of telling a creature to move to places using vanilla AI.

2017-04-13 07:53 UTC, gabizou reviewed
Minor clarification.

2017-04-13 07:53 UTC, gabizou commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +    MoveToBlockAITask setSpeed(double speed);
Is the task mutable? If so , why is there a builder? What differentiation is there from a builder and a finalized task?

2017-04-19 05:35 UTC, me4502 commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +    MoveToBlockAITask setSpeed(double speed);
Many other AITasks have both, however I feel immutability would make more sense.

2017-04-19 06:03 UTC, liach commented on src/main/java/org/spongepowered/api/entity/ai/task/builtin/creature/location/MoveToBlockAITask.java
> +    MoveToBlockAITask setSpeed(double speed);
This is the design of AI Task interfaces.

2018-08-30 09:37 UTC, gabizou commented
Still waiting for whatever @Zidane has cooked up for AI stuff.

2019-05-04 19:56 UTC, ImMorpheus commented
Superseded by https://github.com/SpongePowered/SpongeAPI/pull/1997

2019-05-04 19:56 UTC, closed without merging