EnumValueElement#getValue case fix
SpongePowered/SpongeAPI pull request #1508
Opened 2017-03-01 17:15 UTC by Desetude

This is a fix to https://github.com/SpongePowered/SpongeAPI/issues/1396

At the moment, using EnumValueElement#getValue(String) only works when the enum is all uppercase, this fixes that.

2017-03-03 19:36 UTC, liach commented on src/main/java/org/spongepowered/api/command/args/GenericArguments.java
>                  .map(input -> input == null ? null : input.name())
You can optimize this line to 
```java
.map(input::name)
```
since the elements of the array is guaranteed to be non-null.

2017-03-06 18:58 UTC, liach approved these changes

2017-03-07 02:13 UTC, kashike requested changes

2017-03-07 02:13 UTC, kashike commented on src/main/java/org/spongepowered/api/command/args/GenericArguments.java
> +            return Enum.valueOf(this.type, choice);
This is going to make things fail if user input does not match the enum constant name. A better choice would be to populate a `Map<String, T>` during argument creation, with the `String` key *lowercased*, and simply get the `keySet` for choices, and a simple `get` here.

2017-03-07 12:07 UTC, Desetude commented on src/main/java/org/spongepowered/api/command/args/GenericArguments.java
> +            return Enum.valueOf(this.type, choice);
Should I worry about cases when there are two different values with the same value but different capitilisation, as that is possible with enums. Obviously this is terrible practice, but with the implementation you suggested, there would be no way to differentiate between them.

2017-03-07 15:56 UTC, Deamon5550 commented on src/main/java/org/spongepowered/api/command/args/GenericArguments.java
> +            return Enum.valueOf(this.type, choice);
No I wouldn't worry about that case, usability is more important here.

2017-03-07 16:33 UTC, kashike commented on src/main/java/org/spongepowered/api/command/args/GenericArguments.java
> +            return Enum.valueOf(this.type, choice);
You could warn during population of the map, if you want.

2017-03-07 17:55 UTC, Desetude commented on src/main/java/org/spongepowered/api/command/args/GenericArguments.java
> +            return Enum.valueOf(this.type, choice);
This may be a stupid question, but how should I warn?

2017-03-07 18:19 UTC, kashike requested changes

2017-03-07 18:19 UTC, kashike commented on src/main/java/org/spongepowered/api/command/args/GenericArguments.java
> +            this.values = Arrays.stream(type.getFields())
Why can't you use `getEnumConstants` here?

2017-03-07 18:22 UTC, kashike requested changes

2017-03-07 18:22 UTC, kashike commented on src/main/java/org/spongepowered/api/command/args/GenericArguments.java
> +            return Arrays.stream(this.type.getEnumConstants())
You can simply do `return this.values.keySet();` here.

2017-03-07 18:25 UTC, liach requested changes

2017-03-07 18:25 UTC, liach commented on src/main/java/org/spongepowered/api/command/args/GenericArguments.java
> +                            value -> value,
Use `Function::identity`

2017-03-07 18:27 UTC, liach commented on src/main/java/org/spongepowered/api/command/args/GenericArguments.java
> +                            value -> value.name().toLowerCase(),
Can you use `value.name::toLowerCase`?

2017-03-07 18:34 UTC, Desetude commented on src/main/java/org/spongepowered/api/command/args/GenericArguments.java
> +                            value -> value.name().toLowerCase(),
Don't think that's possible in this situation, unless I'm missing something.

2017-03-07 20:39 UTC, ST-DDT commented on src/main/java/org/spongepowered/api/command/args/GenericArguments.java
> +        private final Map<String, T> values;
Should this map be made immutable?

2017-03-07 20:54 UTC, liach commented on src/main/java/org/spongepowered/api/command/args/GenericArguments.java
> +        private final Map<String, T> values;
It is already immutable since it is created by a collector.

2017-03-07 20:54 UTC, liach approved these changes

2017-03-07 21:04 UTC, ST-DDT commented on src/main/java/org/spongepowered/api/command/args/GenericArguments.java
> +        private final Map<String, T> values;
Nope, its not.
[`Collectors#toMap(...)`](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/util/stream/Collectors.java#1267)

2017-03-07 21:18 UTC, liach commented on src/main/java/org/spongepowered/api/command/args/GenericArguments.java
> +        private final Map<String, T> values;
Why should it be immutable? The code never modifies it in this pull, and the map is already private.

2017-03-08 02:11 UTC, kashike approved these changes

2017-03-08 02:13 UTC, merged