Add error message for @Listener methods.
SpongePowered/SpongeAPI pull request #1513
Opened 2017-03-06 02:23 UTC by JBYoshi

See https://github.com/SpongePowered/SpongeCommon/pull/1233#issuecomment-284154794.

2017-03-06 14:12 UTC, stephan-gh requested changes
:+1:

2017-03-06 14:12 UTC, Minecrell commented on src/ap/java/org/spongepowered/processor/event/ListenerProcessor.java
> +                if (parameters.isEmpty() || isTypeSubclass(parameters.get(0), EVENT_CLASS)) {
This should be `|| !isTypeSubClass(...)` because you want to show the error if the method doesn't have an `Event` as first parameter

2017-03-06 14:12 UTC, Minecrell commented on src/ap/java/org/spongepowered/processor/event/ListenerProcessor.java
> +        return types.isAssignable(event, typedElement.asType());
The order of the arguments for `isAssignable` is wrong here. From the Javadocs:

> returns true if and only if the **first type is assignable to the second**

You want to check if the parameter type extends `Event` which means that you need to check if the parameter is assignable to `Event`. `Event` isn't directly assignable to a subclass of it.

2017-03-06 16:23 UTC, Minecrell commented on src/ap/resources/META-INF/services/javax.annotation.processing.Processor
> +org.spongepowered.processor.plugin.PluginProcessor
While I understand why you move it, I would prefer if it stays in its original package so [we don't break older versions of SpongeGradle](https://github.com/SpongePowered/SpongeGradle/blob/master/src/main/groovy/org/spongepowered/gradle/plugin/SpongePluginBasePlugin.groovy#L37)

2017-03-06 18:57 UTC, liach commented on src/ap/java/org/spongepowered/processor/ProcessorUtils.java
> +}
Need a new line

2017-03-06 18:57 UTC, liach commented on src/ap/java/org/spongepowered/processor/event/ListenerProcessor.java
> +        return types.isAssignable(event, typedElement.asType());
I think it is fine here.

2017-03-06 18:57 UTC, liach commented on src/ap/resources/META-INF/services/javax.annotation.processing.Processor
> +org.spongepowered.processor.plugin.PluginProcessor
We can just ask plugin devs to update SpongeGradle.

2017-03-07 01:14 UTC, JBYoshi commented on src/ap/java/org/spongepowered/processor/ProcessorUtils.java
> +}
@liach Fixed.

2017-03-07 01:14 UTC, JBYoshi commented on src/ap/resources/META-INF/services/javax.annotation.processing.Processor
> +org.spongepowered.processor.plugin.PluginProcessor
@Minecrell Moved back to the original package.

2017-03-07 01:14 UTC, JBYoshi commented on src/ap/java/org/spongepowered/processor/event/ListenerProcessor.java
> +        return types.isAssignable(event, typedElement.asType());
@Minecrell Fixed.

2017-03-07 18:16 UTC, stephan-gh approved these changes

2017-03-07 18:30 UTC, liach approved these changes

2017-03-07 20:48 UTC, ST-DDT approved these changes

2017-03-07 23:41 UTC, kashike approved these changes

2017-03-20 22:57 UTC, me4502 approved these changes

2017-04-13 08:48 UTC, merged