Feed animal event
SpongePowered/SpongeAPI pull request #1522
Opened 2017-03-14 21:12 UTC by Desetude

**SpongeAPI** | [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/1255)

This is a response to the feature request #1382, adding an event that is fired when a player feeds an animal.

2017-03-14 21:53 UTC, kashike requested changes

2017-03-14 21:53 UTC, kashike commented on src/main/java/org/spongepowered/api/event/entity/FeedAnimalEvent.java
> +}
Missing newline.

2017-03-14 21:53 UTC, kashike commented on src/main/java/org/spongepowered/api/event/entity/FeedAnimalEvent.java
> +    /**
Missing newline.

2017-03-14 22:03 UTC, Desetude commented on src/main/java/org/spongepowered/api/event/entity/FeedAnimalEvent.java
> +}
Fixed

2017-03-15 00:30 UTC, liach commented on src/main/java/org/spongepowered/api/event/entity/FeedAnimalEvent.java
> +    ItemType getItem();
You should provide an `ItemStackSnapshot`.

2018-08-30 06:00 UTC, gabizou commented
Might resuscitate this if you're up for absorbing the changes @Zidane for your breeding event changes.

2019-10-08 19:49 UTC, closed without merging

2019-10-09 01:59 UTC, JBYoshi commented
Note: This PR was automatically closed because the `bleeding` branch was deleted. It will need to be reopened to target `api-8` instead.  See https://github.com/SpongePowered/SpongeAPI/pull/1428#issuecomment-539689855.