Refactor Data Registration
SpongePowered/SpongeAPI pull request #1531
Opened 2017-04-06 23:57 UTC by gabizou

This PR intends to do a lot for Data Registration. Ideally the registration transition for developers should be easy, as the object is now a consumable registration object that is registered upon creation.

More description to come.

Likewise, this probably targets a few issues on the API, and also heavily increases the possibility of #1198 coming to fruition.

2017-04-07 03:04 UTC, kashike requested changes

2017-04-07 03:04 UTC, kashike commented on src/main/java/org/spongepowered/api/data/DataAlreadyRegisteredException.java
> +    private final DataManipulatorBuilder<?, ?> builder;
Getters for these fields?

2017-04-07 03:04 UTC, kashike commented on src/main/java/org/spongepowered/api/data/DataManager.java
> +     * <p>Due to the addition of {@link DataRegistration}</p>
Incomplete

2017-04-07 03:04 UTC, kashike commented on src/main/java/org/spongepowered/api/data/DataRegistrationNotFoundException.java
> +    @Nullable private Class<? extends ImmutableDataManipulator<?, ?>> immutableClass;
Getters?

2017-04-07 08:33 UTC, Minecrell commented on src/main/java/org/spongepowered/api/util/TypeTokens.java
> +        throw new RuntimeException("Lolno");
We have this in none our classes, so I don't think throwing an exception is needed here.

2017-04-18 04:47 UTC, merged

2017-04-18 15:19 UTC, Zidane commented on src/main/java/org/spongepowered/api/util/TypeTokens.java
> +import org.spongepowered.api.data.type.*;
Tsk

2017-04-18 18:56 UTC, Deamon5550 commented on src/main/java/org/spongepowered/api/util/TypeTokens.java
> +import org.spongepowered.api.data.type.*;
Do we really need >100 imports for when we really are importing everything in the package.

2017-04-18 20:11 UTC, kinggoesgaming commented
kudos to @gabizou  :smile: