Expose sending a specific page of the Pagination
SpongePowered/SpongeAPI pull request #1539
Opened 2017-04-14 08:39 UTC by ryantheleach

This exposes a method to send a specific page of a pagination.

2017-04-14 09:06 UTC, ST-DDT requested changes
Thats a really nice addition to pagination.

2017-04-14 09:06 UTC, ST-DDT commented on src/main/java/org/spongepowered/api/service/pagination/PaginationList.java
> +     * Send the constructed pagination list to the given source.
Maybe we should state explicitly that it sends the first page. Just to avoid confusion with a random `current` page.

2017-04-14 09:06 UTC, ST-DDT commented on src/main/java/org/spongepowered/api/service/pagination/PaginationList.java
> +     * @param page The page to send
We should mention that the first page is one vs zero as developers count indexes. We should also mention what happens if we use a page after the last one.

2017-04-14 09:09 UTC, ST-DDT commented on src/main/java/org/spongepowered/api/service/pagination/PaginationList.java
> +     * @param page The page to send
Plus maybe a `throws IllegalArgumentException` if the page is zero or negative.

2017-06-11 10:51 UTC, kashike commented on src/main/java/org/spongepowered/api/command/spec/CommandSpec.java
> +        return Optional.ofNullable(extendedDescription);
What are these changes doing in here?

2017-08-10 21:03 UTC, Zidane commented
Closed in favor of: https://github.com/SpongePowered/SpongeCommon/pull/1475

2017-08-10 21:03 UTC, closed without merging