Allow checking if an enchantment is a treasure enchantment or not - Closes #1596
SpongePowered/SpongeAPI pull request #1598
Opened 2017-07-02 04:54 UTC by Meronat

SpongeAPI | [SpongeCommon]()

Closes #1596

2017-07-02 04:55 UTC, kashike requested changes

2017-07-02 04:55 UTC, kashike commented on src/main/java/org/spongepowered/api/item/Enchantment.java
> +    boolean isTreasureEnchantment();
Remove `Enchantment` from the method name.

2017-07-02 04:56 UTC, Meronat commented
I'd be open to a better method name if anyone has one.

2017-07-02 04:57 UTC, Meronat commented on src/main/java/org/spongepowered/api/item/Enchantment.java
> +    boolean isTreasureEnchantment();
I was trying to think of a better name since enchantment seemed redundant, but "isTreasure" doesn't really convey what it is that well.

2017-07-02 04:59 UTC, kashike commented on src/main/java/org/spongepowered/api/item/Enchantment.java
> +    boolean isTreasureEnchantment();
`isTreasure` works fine, javadocs exist for a reason.
`enchantment.isTreasure()`.

2017-07-02 04:59 UTC, Meronat commented on src/main/java/org/spongepowered/api/item/Enchantment.java
> +    boolean isTreasureEnchantment();
Eh it works for me, changing now.

2017-07-03 08:31 UTC, kashike approved these changes

2017-07-03 08:38 UTC, merged