Expand the Instrument/Noteblock API.
SpongePowered/SpongeAPI pull request #1608
Opened 2017-07-14 18:11 UTC by Cybermaxke

**API** | Common

Changes:

- Added the missing `InstrumentType`s, including the `PLING` instrument that isn't officially used but the sound was added.
- Added `InstrumentProperty`, which can be used to retrieve a `InstrumentType` from a `BlockType`. For example `BlockTypes.BONE_BLOCK` would return `InstrumentTypes.XYLOPHONE`.
- Added a key that allows the `InstrumentType` of a `Note`(block) to be overridden.

2017-07-15 06:22 UTC, ST-DDT approved these changes

2017-07-15 09:19 UTC, parlough requested changes
Good additions. Was looking forward to an instrument property and the ability to set an overriden instrument is pretty nice idea/concept.

2017-11-01 09:33 UTC, Cybermaxke commented
Status?

2017-11-01 12:52 UTC, ST-DDT approved these changes

2017-11-01 17:35 UTC, parlough approved these changes

2017-11-30 08:33 UTC, gabizou approved these changes

2017-12-03 02:45 UTC, merged