Feature/userinventory
SpongePowered/SpongeAPI pull request #1624
Opened 2017-08-06 06:42 UTC by Faithcaio

*SpongeAPI* | [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/1401)

Add support for User Inventories

2017-08-06 21:08 UTC, kashike requested changes

2017-08-06 21:08 UTC, kashike commented on src/main/java/org/spongepowered/api/item/inventory/equipment/EquipmentTypeHeld.java
> +public interface EquipmentTypeHeld extends EquipmentType {
`HeldEquipmentType`

2017-08-07 08:19 UTC, Faithcaio commented on src/main/java/org/spongepowered/api/item/inventory/equipment/EquipmentTypeHeld.java
> +public interface EquipmentTypeHeld extends EquipmentType {
should I also rename EquipmentTypeWorn then?

2017-08-07 15:54 UTC, Zidane commented on src/main/java/org/spongepowered/api/item/inventory/equipment/EquipmentTypeHeld.java
> +public interface EquipmentTypeHeld extends EquipmentType {
Yes

2017-08-07 15:56 UTC, Cybermaxke commented on src/main/java/org/spongepowered/api/item/inventory/equipment/EquipmentTypes.java
> +    public static final EquipmentTypeHeld MAINHAND = DummyObjectProvider.createFor(EquipmentTypeHeld.class, "MAINHAND");
`MAIN_HAND` and `OFF_HAND`?

2017-08-07 23:10 UTC, kashike commented on src/main/java/org/spongepowered/api/item/inventory/equipment/EquipmentTypeHeld.java
> +public interface EquipmentTypeHeld extends EquipmentType {
yes

2017-08-11 13:52 UTC, Zidane commented on src/main/java/org/spongepowered/api/item/inventory/entity/UserInventory.java
> +    // TODO getMainPlayerInventory which includes the hotbar
TODO?

2017-08-11 16:36 UTC, Cybermaxke commented on src/main/java/org/spongepowered/api/item/inventory/entity/UserInventory.java
> +    // TODO getMainPlayerInventory which includes the hotbar
When I see `getMain`, I would think it contains the complete bottom inventory, **with** the hotbar. This is also how I implemented in Lantern. If without the hotbar is the way to go, I would also clarify this in the javadocs.

2017-08-11 16:53 UTC, Faithcaio commented on src/main/java/org/spongepowered/api/item/inventory/entity/UserInventory.java
> +    // TODO getMainPlayerInventory which includes the hotbar
Currently it does not contain the Hotbar. 
I want to change that.

2017-08-11 18:22 UTC, Zidane commented on src/main/java/org/spongepowered/api/item/inventory/entity/UserInventory.java
> +    // TODO getMainPlayerInventory which includes the hotbar
@Faithcaio 

See about making that change as it makes sense so long as we get a distinct method for the view of the Inventory WITHOUT the Hotbar.

2017-08-15 16:18 UTC, Zidane commented on src/main/java/org/spongepowered/api/item/inventory/entity/UserInventory.java
> + * It consists of
Docs fail

2017-08-19 22:31 UTC, merged