Bugfixes and improvements for selectors
SpongePowered/SpongeAPI pull request #1645
Opened 2017-09-08 19:31 UTC by rexbut

SpongeAPI | [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/1519)

I am sorry to have recreated a PR but I have no news from @kenzierocks : https://github.com/SpongePowered/SpongeCommon/pull/793

Changes to accommodate the SpongeCommon PR. See that PR for details.

2017-09-11 03:06 UTC, ryantheleach commented
I realize it's code inherited from the current codebase that was left over from when selectors were first introduced, but what was the difference between forced and not forced resolution?

2017-09-16 21:53 UTC, rexbut commented
The forced résolution search entities in all worlds same if there are a location argument in argument list. 
I don't understand in what case, there are useful.

2017-09-28 04:11 UTC, Deamon5550 commented
We need to deprecate the `resolveForce` methods before removing them.

2017-09-28 11:29 UTC, rexbut commented
I have deprecated the methods but the result is now an List <Entity> and there will be a break of compatibility. 
I think nobody currently uses the Selectors because the results is broken. Example (@p: return 2 players)

2017-09-28 14:52 UTC, kashike requested changes

2017-09-28 14:52 UTC, kashike commented on src/main/java/org/spongepowered/api/text/selector/Selector.java
> +}
newline at end of file please

2017-09-28 18:19 UTC, Deamon5550 commented
Yeah thats unfortunate fine. Can you also add an @deprecated tag in the javadoc to point people to just use `resolve` instead now on the resolveForce methods.

2018-01-01 09:11 UTC, Meronat commented
I'm sorry for this not receiving much attention, will definitely see more soon with API 8!

2018-02-07 21:25 UTC, Katrix- commented
Thoughts on specifying that the parse method throws an `IllegalArgumentException` in the javadocs. Both so that others using it know what to look for as an error, and to make sure that other future implementations don't do something else?

2018-08-12 10:26 UTC, dualspiral commented
Superseded by https://github.com/SpongePowered/SpongeAPI/pull/1883

2018-08-12 10:26 UTC, closed without merging