Fix ContextValue Annotation for Event Listeners
SpongePowered/SpongeAPI pull request #1648
Opened 2017-09-15 18:42 UTC by gabizou

To be described.

Long story short: Since the Cause and Context PR merge, this annotation which *replaced* `@Named`, we've been unable to reproduce the feature set due to the language requirements that annotations are utilizing constants at *compile* time and not *runtime*. As such, it's not feasible to use for example:
```java
@Listener
public void onChange(ChangeBlockEvent.Place event, @ContextValue(EventContextKeys.OWNER.getName()) Player player) {
 // foo
}
```
This will result in a compile time error due to the lack of constants in this case.

This adds the constants to be used and some fuzzy string matching on the context to perform the job as expected.

2017-09-15 22:06 UTC, Deamon5550 requested changes

2017-09-15 22:06 UTC, Deamon5550 commented on src/main/java/org/spongepowered/api/event/filter/cause/ContextValue.java
> +     * <p>
Extra <p>

2017-09-15 22:06 UTC, Deamon5550 commented on src/main/java/org/spongepowered/api/event/cause/EventContextKeys.java
> +        public static final String BLOCK_HIT = "BLOCK_HIT";
Should just make these names be the ids as in https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/registry/type/event/EventContextKeysModule.java#L78

2017-09-15 22:06 UTC, Deamon5550 commented on src/main/java/org/spongepowered/api/event/cause/EventContext.java
> +        final String simplified = possibleName.toLowerCase().replace('_', ' ');
Just have this get the EventContextKey from the registry by id, check that the key's type matches klass, and then return the get.

2017-09-15 22:10 UTC, Deamon5550 commented
Thinking further not sure why the new method on `EventContext` is even needed, is basically just a helper over getting the key from the registry, but without the caching that the proper way of doing this provided. Plugins should just be getting the key from the registry by id if they wish, allowing them to handle any error from the key not existing there. This method provides nothing new while simultaneously lowering the performance and masking any error from the key not existing.

2018-01-31 23:46 UTC, Zidane commented
After looking at this again over time, I agree with @Deamon5550 's thoughts.

2018-01-31 23:46 UTC, closed without merging