Make StateMatcher serializable
SpongePowered/SpongeAPI pull request #1678
Opened 2017-10-31 02:28 UTC by Katrix-

Makes StateMatcher serializable.

I'm a bit unsure about where to register the builder. Anyone mind pointing that out to me? Closes #1528.

2017-10-31 02:55 UTC, liach commented on src/main/java/org/spongepowered/api/block/BlockState.java
> +            for(Map.Entry<DataQuery, Object> entry : entries.entrySet()) {
space between `for`, `if` and `(`

2017-10-31 02:55 UTC, liach commented on src/main/java/org/spongepowered/api/block/BlockState.java
> +                    blockType.getTrait(traitId).ifPresent(t -> trait((BlockTrait)t, (Comparable)obj));
Suppress rawtypes warning?

2017-10-31 08:57 UTC, Katrix- commented
Of, fixed.

2017-11-05 05:53 UTC, gabizou requested changes
If we're making it serializable, I'd rather we move the implementation to implementation. Since this is no longer just a simple state matcher, I'd like it to exist where we don't expose what keys are being used, etc.

2017-11-27 01:18 UTC, ryantheleach commented
With the flattening coming in 1.13 I see us needing a matcher that fulfills this role, is human-serializable, but uses legacy block properties or Data Keys/Values instead.

Nearly all cases where the old State Matcher would have been useful, are changed for 1.13 to either just work with Blocks rather then blockstates, or no longer have implementation available to query.

e.g. there is no color property on wool anymore.

2017-11-27 08:48 UTC, gabizou commented
> With the flattening coming in 1.13 I see us needing a matcher that fulfills this role, is human-serializable, but uses legacy block properties or Data Keys/Values instead.
> 
> Nearly all cases where the old State Matcher would have been useful, are changed for 1.13 to either just work with Blocks rather then blockstates, or no longer have implementation available to query.

Hence why this should be moved to implementation. So that implementation can support whatever we need to support, and warn appropriately.

2018-02-11 09:00 UTC, ryantheleach commented
This is a good start, but I'd like to see a potential BlockMatcher as well, 

That can handle 
1. (1.13) tags e.g. `#minecraft:anvil`
2. BlockTypes minecraft:anvil (This is done I believe)
3. partialStates minecraft:anvil[damage=0] (This is done I believe)
4. DataKeys, Maybe interacting with https://github.com/SpongePowered/SpongeAPI/pull/1715

No matter what, the serialization format has to be relatively simple, and understandable to people who have dealt with minecraft data previously. e.g. /testblock

2018-02-11 17:15 UTC, Katrix- commented
I've finished most of the things I've been working on lately so I think I should be able to get some work on this and other stuff I started today and tomorrow.

2018-08-30 03:48 UTC, gabizou commented
This needs updating since `BlockStateMatcher` has moved and is now just an interface. I'll gladly merge once the update has been done, and there's a test plugin added to the implementation. I don't believe this needs 1.13 to be available prior to merging.

2018-12-14 21:04 UTC, Katrix commented
Don't think I ever mentioned that I updated this.

2019-01-27 07:33 UTC, gabizou approved these changes

2019-10-08 19:49 UTC, closed without merging