Move text implementation to the implementation
SpongePowered/SpongeAPI pull request #1744
Opened 2018-01-22 22:35 UTC by kashike

[**SpongeAPI**](https://github.com/SpongePowered/SpongeAPI/pull/1746) | [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/1724)

2018-01-22 22:43 UTC, Meronat commented
Some related PRs:

https://github.com/SpongePowered/SpongeAPI/pull/1477
https://github.com/SpongePowered/SpongeAPI/pull/1634

Maybe for consideration:

https://github.com/SpongePowered/SpongeAPI/pull/1424

2018-01-23 07:24 UTC, gabizou requested changes
We shouldn’t have any more reason to use the factory. A combination of explicit builder methods like ‘LiteralText.builder()’ or ‘Text.literal()’

2018-01-23 07:24 UTC, gabizou commented on src/main/java/org/spongepowered/api/GameRegistry.java
> +    TextFactory getTextFactory();
What is this used for?

2018-01-23 07:24 UTC, gabizou commented on src/main/java/org/spongepowered/api/GameRegistry.java
> +    TextFactory getTextFactory();
That needs to exist in api?

2018-01-23 07:24 UTC, gabizou commented on src/main/java/org/spongepowered/api/text/Text.java
> +        return Sponge.getRegistry().getTextFactory().emptyText();
Why do we use the factory instead of a builder?

2018-01-23 07:24 UTC, gabizou commented on src/main/java/org/spongepowered/api/text/Text.java
> +        return Sponge.getRegistry().getTextFactory().literal(content);
This honestly feels like we can static builder the individualized texts like all other builders instead of using a factory

2018-01-24 02:28 UTC, liach commented on src/main/java/org/spongepowered/api/text/LiteralText.java
> +        Builder from(Text value);
Can a literal text's builder copy from any text? How does that work?

2018-08-10 06:38 UTC, merged