Add text replacement methods
SpongePowered/SpongeAPI pull request #1755
Opened 2018-01-30 05:23 UTC by pie-flavor

These are very much needed, given the relative underpoweredness of `TextTemplate`.

2018-01-30 13:30 UTC, ryantheleach commented
@pie-flavor Is this still Work In Progress? if so use `~wip` to mark your issue as Work In Progress or else use `~qa` to mark it as ready for Quality Assurance, if you wish it to be reviewed / tested by contributors / the community.

2018-01-30 16:05 UTC, pie-flavor commented
-qa

2018-01-30 16:08 UTC, pie-flavor commented
~qa

2018-02-06 09:53 UTC, The-Defman commented
Is Text not meant to be imutable: Represents an immutable tree-structure of formatted (text) components. Each instance consists of content and a list of children texts appended after the content of this text. The content of the text is available through one of the subclasses.

2018-02-06 10:19 UTC, ryantheleach commented
Sure, but it's a utility function for something that is inherently difficult to do yourself 100% correctly the first time. 

Strings are immutable too, doesn't stop them having replace.

My 2c.

2018-02-06 11:20 UTC, dualspiral commented
I don't see a problem with it as long as the javadocs make it clear (in both the body and the returns statement) that the method returns a copy of the `Text` object with the specified replacements.

2018-02-06 11:35 UTC, pie-flavor commented
@The-Defman I'm confused - where's the issue? The original text never gets modified.

@dualspiral I'll add that, though originally I never thought it could be an issue - anyone using Text.replace has inevitably used String.replace which behaves the same way.

2018-02-06 19:08 UTC, kashike requested changes

2018-02-06 19:08 UTC, kashike commented on src/main/java/org/spongepowered/api/text/Text.java
> +        Text t = this.children.isEmpty() ? this : this.toBuilder().removeAll().append(this.children.stream()
Please give this a longer name - single character variables should be reserved for `for`.

2018-02-06 19:08 UTC, kashike commented on src/main/java/org/spongepowered/api/text/Text.java
> +    public Text replace(Pattern oldValue, Text newValue, boolean lossy) {
Could you add a few comments to this method explaining what's going on? Will be nice for the next person who works on this.

2018-05-04 15:08 UTC, randombyte-developer commented
Can this be added to the next 7.x release or is that against semver?

2018-05-05 15:30 UTC, pie-flavor commented
No API methods get broken, so 7.x should be a valid target.

2018-08-30 05:38 UTC, gabizou commented
Needs to be updated since the text was refactored.

2018-08-30 11:09 UTC, Cybermaxke commented
@gabizou This targets API 7

2018-08-30 11:15 UTC, ImMorpheus commented
@Cybermaxke you need to change the target branch to stable-7 then

2019-02-02 01:41 UTC, pie-flavor commented
Oh good, the git history got clonked. Is this worth pursuing in its current state? Will there be another API 7 release?

2019-02-03 18:42 UTC, ImMorpheus commented
@pie-flavor Yes, please update and rebase

2019-03-05 18:22 UTC, pie-flavor commented
Looks all good from here.

2019-03-05 18:33 UTC, XakepSDK commented
Maybe `replace(Text, Text)`?

2019-03-06 16:51 UTC, pie-flavor commented
Properly searching for a Text would require remembering the effective formatting of the text in addition to the Text's own formatting, and additionally parsing children, greatly complicating the algorithm. And there wouldn't really be a point in a Text argument that's only ever used via toPlain.

2019-07-06 16:14 UTC, ImMorpheus approved these changes
Working as intended

2019-07-06 16:14 UTC, merged

2019-07-11 13:13 UTC, Lignium commented
You need to add these methods to API 8.