Add KeybindText
SpongePowered/SpongeAPI pull request #1763
Opened 2018-02-03 22:05 UTC by kashike

2018-02-04 09:23 UTC, Minecrell commented
Is an empty keybind text valid? Otherwise we should check this and eventually make the parameter required for the builder already (this is how it seems to be for the other text classes).

2018-02-04 12:30 UTC, Cybermaxke commented
Maybe there should be a `CatalogType` for the supported keys? There is also a `key.invalid` key that can be used in cases that the key binding is unknown.

2018-02-09 17:36 UTC, gabizou requested changes
WHAT IS A KEYBIND TEXT?! Almost none of the descriptions so far have told me how it's used And the PR has no description, so that's a plus.

2018-02-09 17:36 UTC, gabizou commented on src/main/java/org/spongepowered/api/text/KeybindText.java
> +     * Constructs a new immutable {@link LiteralText} for the keybind
javadoc fail much?

2018-02-09 17:36 UTC, gabizou commented on src/main/java/org/spongepowered/api/text/KeybindText.java
> + * Represents a {@link Text} containing a keybind.
a keybind that is documented by saying key bind makes a lot of sense. How do I use a key bind? "Oh, just make a key bind and use it!"

2018-02-11 06:37 UTC, ryantheleach commented on src/main/java/org/spongepowered/api/text/KeybindText.java
> + * Represents a {@link Text} containing a keybind.
Represents a {@link Text} placeholder that on the client, replaces string keynames, eg: "key_key.swapHands" will be replaced with "F" on the client, see TranslatableText.

/tellraw @a ["",{"text":"Press "},{"keybind":"key.swapHands"},{"text":" to pay respects"}]
Press F to pay respects.

2018-07-08 18:12 UTC, Aaron1011 commented
What's the status of this PR? With the way that the Text implementation is currently setup, we can't properly handle mods using `TextComponentKeybind`, since we can't represent it as a `Text`.

2018-08-04 21:35 UTC, ryantheleach commented
LGTM as-is (havn't checked it out and tested locally)

Is there something blocking this from being merged? @gabizou Your complaint earlier about the JD is just, but I don't think it should hold this up from merging.

2018-08-30 05:22 UTC, gabizou commented
I think this will be API 8, if expected to be available then as Text has moved to implementation.

2018-08-30 09:39 UTC, ryantheleach commented
@gabizou note, it's needed for stable as well, due to "What's the status of this PR? With the way that the Text implementation is currently setup, we can't properly handle mods using TextComponentKeybind, since we can't represent it as a Text."

It caused aaron various issues.

2020-06-28 04:23 UTC, Zidane commented
@kashike Is this complete? Or do you plan to work on this anymore?

2020-06-28 21:28 UTC, Zidane commented
Closing as we're going in a slightly different direction in api-8 and won't be adding major changes to api-7 at this point.

2020-06-28 21:28 UTC, closed without merging