Change SkinData to use a custom ProfileProperty
SpongePowered/SpongeAPI pull request #1836
Opened 2018-05-23 23:50 UTC by Aaron1011

It's often useful to be able to set an arbitrary signed
skin payload for a Humanoid:

* Plugins may want to use a skin that is not currently set on any
player
* The Mojang skin API has notoriously strict IP-based rate-limiting.
Servers, especially those that are part of a larger network, may
wish to implement their own caching system.

This commit allows plugins to set use valid skin ProfileProperty
with SkinData, rather than being constrained to use a skin currently
in use by a specific player.

2018-05-24 02:17 UTC, kashike requested changes

2018-05-24 02:17 UTC, kashike commented on src/main/java/org/spongepowered/api/data/key/Keys.java
> +    public static final Key<Value<ProfileProperty>> SKIN = DummyObjectProvider.createExtendedFor(Key.class,"SKIN_UNIQUE_ID");
You forgot to change the dummy text.

2018-05-24 02:17 UTC, kashike commented on src/main/java/org/spongepowered/api/profile/property/ProfileProperty.java
> +     * The name of the special 'textures' property. This is
There's nothing "special" about it:
```java
    /**
     * The name of the {@code textures} property.
     *
     * @see SkinData
     */
```

2018-05-24 02:18 UTC, me4502 commented
Does this allow setting it on skull items? If so, hella keen :tada:

2018-05-24 02:25 UTC, Aaron1011 commented
Skulls use [RepresentedPlayerData](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/manipulator/mutable/RepresentedPlayerData.java), which takes a full `GameProfile`.

2018-05-24 08:28 UTC, gabizou commented on src/main/java/org/spongepowered/api/data/manipulator/immutable/entity/ImmutableSkinData.java
> + * Represents the UUID of the skin for a {@link Humanoid}.
Is it still the UUID in this case?

2018-05-24 11:08 UTC, XakepSDK commented
Add ability to modify skin parts

2018-05-24 11:13 UTC, Aaron1011 commented
@XakepSDK: That should go in a different PR.

2018-05-24 21:55 UTC, Aaron1011 commented
My corresponding SpongeCommon PR makes `SkinData` applicable to *players*, as well as humans. Both the player themself and other players on the server will see the updated skin.

Thanks to @McLive for showing how this could be done in their [SkinsRestorerX plugin](https://github.com/McLive/SkinsRestorerX)

2018-05-25 09:12 UTC, kashike commented on src/main/java/org/spongepowered/api/profile/property/ProfileProperty.java
> +     * This is used with {@link SkinData} to set the skin of a {@link Humanoid}
`<p>This is used with {@link SkinData} to set the skin of a {@link Humanoid}.</p>`

2018-05-29 02:14 UTC, kashike commented on src/main/java/org/spongepowered/api/profile/property/ProfileProperty.java
> +     * This is used with {@link SkinData} to set the skin of a {@link Humanoid}
@Aaron1011

2018-05-29 14:54 UTC, gabizou commented on src/main/java/org/spongepowered/api/data/manipulator/immutable/entity/ImmutableSkinData.java
> +     * If it is <code>false</code>, then the tab list will not be modified.
New paragraph needs `<p>`.

2018-05-30 20:53 UTC, Aaron1011 commented
@gabizou @kashike I've made the javadoc changes you requested.

2018-06-03 19:09 UTC, Aaron1011 commented
Pinging @SpongePowered/developers and @XakepSDK for final review.

If no one else wants any other changes, I'm planning to merge this in a few days.

2018-06-05 04:12 UTC, initramfs commented
Forgive my ignorance but will this change allow for updating skins for a subset of players? There are use cases where it is beneficial or even required where a group of players sees a specific skin for a human whereas a different group sees a different skin.

Another example would be where a player sees his/her own skin differently as what other players would see him/her (for example when designating teams via skins).

2018-06-05 15:03 UTC, Aaron1011 commented
@initramfs: Unforuntately, no. This will probably need to wait until @kashike's Contextual Data system is ready.

2018-06-11 15:54 UTC, gabizou approved these changes

2018-06-29 00:36 UTC, Aaron1011 commented
Merged in https://github.com/SpongePowered/SpongeAPI/commit/a3431307f06996321489b69664b16202e8806042.

2018-06-29 00:36 UTC, closed without merging