Add plugin adapters.
SpongePowered/SpongeAPI pull request #1990
Opened 2019-04-17 16:21 UTC by Cybermaxke

Supports alternate plugin instantiation and injections. Can be used e.g. for kotlin/scala object support, kotlin delegate property injections, custom plugin injections, etc.

I am going to write a test project to demonstrate how it can be used. SpongeVanilla support will follow once it's successfully tested on SpongeForge.

2019-04-17 19:58 UTC, XakepSDK commented
Can you also add support for guice modules for plugins?
E.g. developer specifies module class in plugin annotation and then impl. installs that module for plugin's injector.

2019-04-18 08:45 UTC, kashike requested changes

2019-04-18 08:45 UTC, kashike commented on src/main/java/org/spongepowered/api/plugin/PluginAdapter.java
> +    final class Default implements PluginAdapter {
Should not be implemented here - should be an empty interface, and implemented elsewhere.

2019-04-18 08:45 UTC, kashike requested changes

2019-04-18 08:45 UTC, kashike commented on src/main/java/org/spongepowered/api/plugin/PluginAdapter.java
> +    <T> Injector getInjector(PluginContainer pluginContainer, Class<T> pluginClass, Injector defaultInjector, List<Module> pluginModules);
`createInjector`

2019-04-30 05:27 UTC, killjoy1221 commented
👎 for cluttering up the `@Plugin` class.

If we go the route that FML went, the annotation would be specific to the default java loader. The Kotlin loader would have to provide its own loading scheme.

I would also like to see this done as a [ServiceLoader](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html).

2019-04-30 19:12 UTC, Cybermaxke commented
I don't think it's cluttering the annotation, it's not like it's required which could clutter the usage. Same goes for the modules. We could always move them to separate annotations if needed.

Going down the road of reimplementing the complete loader is going to complicate things, you'll need to reimplement the `PluginContainer`, handle class loading, annotation scanning. And in the end, we'll just end up with yet another `Plugin` annotation. I also don't see how this complete control is going to add any more value than what's already possible by injector transformations.

The goal of the plugin adapters isn't to reimplement of what's already there, replacing the complete loading system isn't worth it IMO.

If you also look at what forge uses it for in there scala adapter, it's just to provide language specific injections. Which can easily be handled by guice.

2019-05-02 21:12 UTC, pie-flavor commented
We'd need some way of instantiating PluginContainer in a safe way if we had separate annotations. This actually seems like *less* bloat to add another field to Plugin.

2019-05-02 21:21 UTC, Katrix commented
Will there be any way to avoid having to interface with Guice so that I can wire up by stuff statically? I don't really see any value in this from a Scala point of view at least if I can't.

Also, a bit unsure what you're talking about with the Scala adapter for Forge injecting language specific stuff. It doesn't inject anything. No mod or plugin annotation, or anything like that. You specify the name of the plugin object in the toml file, and go on your way.

2019-05-02 21:33 UTC, Cybermaxke commented
You don't have to use guice injections in your scala plugin, sponge uses it to construct the instance. You can register a provider and implement it however you like.

As for the scala adapter, I looked at a older version that didn't use any config, when it was still in Forge.

I also don't feel like exposing the construction of `PluginContainer`s is a good idea, maybe a way to register a alternate annotation and map those to PluginContainer values is better? And optionally registering adapters, etc.
E.g. 
```kotlin
annotation class KotlinPlugin(val id: String, val name: String)

// Find a way to register annotations?
registry.registerPluginAnnotation(KotlinPlugin::class.java, KotlinPlugin::id).mapName(KotlinPlugin::name).adapter(MyAdapter())
```

2019-06-06 06:38 UTC, pie-flavor commented
Actually it would be nice to not have to use the Plugin annotation. This API could then be extended to stuff not even Java-based, such as scripting plugins, so they could register each script set as a plugin.

2020-06-09 09:30 UTC, dualspiral commented
Are we going to revisit this for API 7, or are we just going to leave this for the [Launcher](https://github.com/SpongePowered/plugin-spi) project in API 8?

2020-06-28 15:20 UTC, Zidane commented
I am closing this.

As dual linked, plugin-spi is very lightweight and super simple to implement a language loading service for other JVM based languages (or even ones that aren't anchored in the JVM). You can easily add kotlin/scala features to your own service.

2020-06-28 15:20 UTC, closed without merging