Add more Selector API
SpongePowered/SpongeAPI pull request #2331
Opened 2021-04-20 10:20 UTC by jpenilla

Sponge | SpongeAPI

Adds methods to `Selector` to retrieve
- The input string used to create the selector (if it exists)
- Whether it is able to select players only or any entity type
- The limit for number of entities it can select

These APIs are particularly useful for external command frameworks when combined with the `ENTITY` `ClientCompletionKey`.

2021-04-20 11:00 UTC, dualspiral requested changes

2021-04-20 11:00 UTC, dualspiral commented on src/main/java/org/spongepowered/api/command/selector/Selector.java
> +    Optional<String> inputString();
No - a selector should have no link with an input string whatsoever. This is something that should be handled by the external parser itself - they should store the string if its of interest, not this selector.

2021-04-20 11:22 UTC, jpenilla commented on src/main/java/org/spongepowered/api/command/selector/Selector.java
> +    Optional<String> inputString();
I've removed the input string API

2021-04-24 09:18 UTC, dualspiral commented
I've reworded the Javadocs slightly and made them conform to our style - figured it'd be better to do that rather than get you to do it and waste time doing so.

https://github.com/SpongePowered/SpongeAPI/commit/9273ea9a33c7c239ec95862b07a31a5e7a87e397

2021-04-24 09:18 UTC, closed without merging